CHAR_NAMES = {'Devil Jin': ['dvj', 'deviljin', 'devil-jin', 'devil_jin'],
              'Anna': ['anna', 'ana'],
              'Armor King': ['armorking', 'armor', 'ak', 'armor_king', 'armor-king', 'amk'],
              'Lei': ['lei'],
              'Steve': ['steve', 'ste'],
              'Eddy': ['eddy', 'edy'],
              'Claudio': ['claudio', 'cld'],
              'Bob': ['bob'],
              'Katarina': ['katarina', 'kat'],
              'Asuka': ['asuka', 'asu'],
              'Lee': ['lee'],
              'Heihachi': ['heihachi', 'hei'],
              'Eliza': ['eliza', 'elz'],
              'Kuma': ['kuma', 'kum', 'panda', 'pan'],
              'Lili': ['lili', 'lil'],
              'Jack 7': ['jack', 'jck', 'jack-7', 'jack 7', 'jack_7'],
              'Dragunov': ['dragunov', 'drag', 'dra'],
              'Law': ['law'],
              'Geese': ['geese', 'ges'],
              'Master Raven': ['raven', 'mrv', 'masterraven', 'master-raven', 'master_raven'],
              'Xiaoyu': ['xiaoyu', 'xiao', 'ling'],
              'Noctis': ['noctis', 'noc'],
              'Yoshimitsu': ['yoshimitsu', 'yoshi', 'yos'],
              'Gigas': ['gigas', 'ggs'],
              'Marduk': ['mar','marduk','mdk'],
              'Bryan': ['bryan', 'bry'],
              'King': ['king', 'kin'],
              'Jin': ['jin'],
              'Julia': ['julia', 'jul'],
              'Miguel': ['miguel', 'mig'],
              'Feng': ['feng', 'fen'],
              'Josie': ['josie', 'jos'],
              'Kazuya': ['kazuya', 'kaz'],
              'Kazumi': ['kazumi', 'kzm'],
              'Paul': ['paul', 'pau'],
              'Alisa': ['alisa', 'ali'],
              'Lucky Chloe': ['chloe', 'dnc', 'lck', 'luckychloe', 'lucky-chloe', 'lucky_chloe', 'lucky'],
              'Akuma': ['akuma', 'aku', 'gouki'],
              'Nina': ['nina', 'nin'],
              'Negan': ['negan', 'neg', 'ngn', 'nig'],
              'Shaheen': ['shaheen', 'shn'],
              'Leo': ['leo'],
              'Hwoarang': ['hwoarang', 'hwo'],
              'Lars': ['lars', 'lar']}
